---
- name: Create instances
  hosts:  elastic_slave
  gather_facts: no
  connection: local
  vars_files:
    - vars/instance/vars.yml
  tasks:
    - include_tasks: roles/instance/tasks/create.yml
      run_once: true

- name: Setup instances
  hosts:  elastic_slave
  become: yes
  become_user: root
  gather_facts: no
  tasks: 
    - include_tasks: roles/instance/tasks/setup.yml

- name: Create Disk
  hosts: elastic_slave
  gather_facts: no
  connection: local
  vars_files:
    - vars/instance/vars.yml
  tasks:
    - include_tasks: roles/instance/tasks/create_disk.yml
      run_once: true

- name: Setup Disk
  hosts: elastic_slave
  become: yes
  become_user: root
  gather_facts: no
  vars_files:
    - vars/instance/vars.yml
  tasks:
    - include_tasks: roles/instance/tasks/setup_disk.yml

- name: Install Elastic Slave
  hosts: elastic_slave
  become: yes
  become_user: root
  gather_facts: no
  vars_files:
    - vars/instance/vars.yml
    - vars/elasticsearch/vars.yml
    - vars/elasticsearch/token
  tasks: 
    - include_tasks: roles/elasticsearch/tasks/main.yml

- name: Install Monitor
  hosts: elastic_slave
  become: yes
  become_user: root
  gather_facts: no
  vars_files:
    - vars/monitor/vars.yml
  tasks:
    - include_tasks: roles/monitor/tasks/main.yml

- name: Install Google Ops Agent
  hosts: elastic_slave
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - include_tasks: roles/ops_agent/tasks/main.yml
