---
- name: Delete instances
  hosts: gce
  gather_facts: no
  connection: local
  vars_files:
    - vars/instance/vars.yml
  tasks:
    - include_tasks: roles/instance/tasks/delete.yml
      run_once: true
